---
- hosts: master
  gather_facts: true 
  become: yes
  roles:
    - role: common
      tags: cmn
    - role: cri
      tags: cri
    - role: k8s-server
      tags: k8s
    - role: haproxy
      tags: haproxy
    - role: keepalived
      tags: keepalived
