---
# tasks file for k8s-server
- name: Download and dearmor Kubernetes APT key
  become: yes
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes APT repository
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /
    mode: '0644'

- name: Run apt-get update 
  become: yes
  shell: apt-get update

- name: Install kubeadm, kubelet
  apt:
    pkg:
    - kubelet
    - kubeadm
    state: present
